### ISSUE TITLE
Apply for some pretrain images

### ISSUE THREAD

**Issue by BUAADreamer** [RupertLuo/VoCoT#2]
Thanks for your great work!!! We found that some of the images of mmc4 and grit can't be downloaded or the download speed is very slow. Could you please provide the link to download the images of these two datasets? I can provide my personal baidu disk for you to use (I have supervip) !

**Comment by Junction4Nako** [comment]
Thanks for acknowledging our work! But unfortunately, we can not directly provide the image files to you, the size of all images is quite large and we can not afford the cost to transfer it, so sorry for that TAT. But we recommend you to use this useful tool: https://github.com/rom1504/img2dataset to download the images, which greatly helped us for the data preparation!

**Comment by BUAADreamer** [comment]
Ok, thanks
